# Basic
title: Weasley’s Blog
subtitle: 人走茶凉，乘热饮用
welcome_message: <a href="http://blog.csdn.net/weasleyqi" target="_blank">My CSDN Blog</a>
description: Hi,I’m weasley. A iOS engineer lived in SuZhou. Welcome to my blog.
creator: <a href='http://blog.csdn.net/weasleyqi'>@Weasley</a>

url: "https://weasleyqi.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: '#blog'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: u/1652114337
    github: weasleyqi
    twitter: weasleyqi
    gplus: weasleyqi
    mail: weasleyqi@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
